# Generated by Django 2.2 on 2021-07-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_studentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
