# Generated by Django 2.2 on 2021-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=420, unique=True)),
                ('home_university', models.CharField(max_length=60)),
                ('outgoing_university', models.CharField(max_length=60)),
                ('register_date', models.DateTimeField()),
            ],
        ),
    ]
