# Generated by Django 2.2 on 2021-07-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210723_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegisterManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentregister',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='studentregister',
            name='password',
        ),
    ]
